name: Build WAR on Branch Push

on:
  push:
    branches:
      - feature-pagination

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 8 # <-- Changed to JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8' # <-- Changed to '8'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package

      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-web-app
          path: target/*.war
