name: Java CI/CD with WAR Deployment

on:
  push:
    branches: [ feature-pagination ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
    
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
    
    - name: Create db_properties.xml
      run: |
        mkdir -p src/main/resources
        cat > src/main/resources/db_properties.xml << EOF
        <?xml version="1.0" encoding="UTF-8"?>
		<!DOCTYPE configuration PUBLIC "-//mybatis.org//DTD Config 3.0//EN"     "http://mybatis.org/dtd/mybatis-3-config.dtd">
		<configuration>

			<environments default="development">

				<environment id="intelehealthAwsTest">
					<transactionManager type="JDBC"/>
						<dataSource type="POOLED">
							<property name="poolMaximumActiveConnections" value="6"/>
							<property name="poolMaximumIdleConnections" value="3"/>
							<property name="poolMaximumCheckoutTime" value="24000"/>
							<property name="poolPingConnectionsNotUsedFor" value="24000"/>
							<property name="poolPingEnabled" value="true"/>
							<property name="poolPingQuery" value="select 1"/>
							<property name="driver" value="com.mysql.cj.jdbc.Driver"/>
							<property name="url" value="jdbc:mysql://127.0.0.1:3306/openmrs?autoReconnect=true&amp;useSSL=FALSE"/>
							<property name="username" value="root"/>		
							<property name="password" value="i10hi1c"/>

						</dataSource>
				</environment>

			</environments>
			<mappers>
				<mapper class="com.emrmiddleware.dmo.PatientDMO"/>
				<mapper class="com.emrmiddleware.dmo.VisitDMO"/>
				<mapper class="com.emrmiddleware.dmo.EncounterDMO"/>
				<mapper class="com.emrmiddleware.dmo.ObsDMO"/>
				<mapper class="com.emrmiddleware.dmo.LocationDMO"/>
				<mapper class="com.emrmiddleware.dmo.ProviderDMO"/>
				<mapper class="com.emrmiddleware.dmo.PersonDMO"/>
				<mapper class="com.emrmiddleware.dmo.UserCredentialsDMO"/>
				<mapper class="com.emrmiddleware.dmo.MindmapDMO"/>

			</mappers>
		</configuration>

        EOF
    
    - name: Run tests
      run: mvn clean test
    
    - name: Build WAR file
      run: mvn clean package -DskipTests
